# Shark Attack Project

In [55]:
shark_attack['year']

0       2026.0
1       2026.0
2       2026.0
3       2026.0
4       2026.0
         ...
7120       0.0
7121       0.0
7122       0.0
7123       0.0
7124       0.0
Name: year, Length: 7125, dtype: float64

In [56]:
shark_attack['year'] = shark_attack['year'].astype('Int64')

In [57]:
shark_attack['year']

0       2026
1       2026
2       2026
3       2026
4       2026
        ...
7120       0
7121       0
7122       0
7123       0
7124       0
Name: year, Length: 7125, dtype: Int64

In [58]:
shark_attack['year'].nunique()

261

In [59]:
shark_attack['year'].value_counts()

year
2015    143
2017    141
2016    133
0       129
2011    128
       ...
1518      1
1500      1
1000      1
77        1
5         1
Name: count, Length: 261, dtype: Int64

In [60]:
int(shark_attack['year'].mean())

1936

In [61]:
shark_attack['year'].median()

np.float64(1987.0)

In [62]:
shark_attack['year'].describe()

count         7123.0
mean     1936.649586
std       269.808177
min              0.0
25%           1948.0
50%           1987.0
75%           2010.0
max           2026.0
Name: year, dtype: Float64

In [72]:
shark_attack['year'] = shark_attack['year'].replace(0, 1987)

shark_attack['year'].value_counts().loc[lambda years: years.index < 2010]

year
1987    164
2008    122
2009    120
2007    113
2006    103
       ...
1691      1
1640      1
1638      1
1637      1
1617      1
Name: count, Length: 233, dtype: Int64

In [74]:
shark_attack = shark_attack[shark_attack['year'] >= 2010]

In [65]:
shark_attack['fatal_y/n']

0       Y
1       N
2       N
3       N
4       N
       ..
7120    Y
7121    Y
7122    Y
7123    Y
7124    Y
Name: fatal_y/n, Length: 7113, dtype: str

In [70]:
shark_attack['fatal_y/n'].value_counts()

fatal_y/n
n          4982
y          1492
unknown      68
f             5
m             3
nq            1
2017          1
y x 2         1
Name: count, dtype: int64[pyarrow]

In [67]:
shark_attack['fatal_y/n'] = (shark_attack['fatal_y/n'].astype('string').str.strip().str.lower())

In [68]:
shark_attack['fatal_y/n'].value_counts()

fatal_y/n
n          4982
y          1492
unknown      68
f             5
m             3
nq            1
2017          1
y x 2         1
Name: count, dtype: int64[pyarrow]

In [ ]:
shark_attack['fatal_y/n'] = (shark_attack['fatal_y/n'].astype('string').str.strip().str.lower().replace({
        'yes': 'y',
        'no': 'n',
        'yess': 'y',
        'n/a': pd.NA,
        'nan': pd.NA,
        'unknown': pd.NA
    })
)

shark_attack['fatal_y/n'].value_counts(dropna=False)

In [75]:
shark_attack['country'].value_counts()

country
USA             844
AUSTRALIA       361
SOUTH AFRICA     81
BAHAMAS          60
Australia        56
               ...
KENYA             1
AZORES            1
SOUTH KOREA       1
MALTA             1
MADAGASCAR        1
Name: count, Length: 123, dtype: int64

In [13]:
shark_attack.head(20)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,Greg O'Neil,M,63,...,Great White Shark 6m (20ft),Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,Unknown Male,M,?,...,Great White Shark,Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,Unknown Austrian Tourist,F,37,...,Unknown,Kevin McMurray Trackingsharks.com: Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,Mel Ismail,M,50's,...,Unknown,Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,Wants to remain anonymous,M,24,...,Tiger Shark suspected,Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2nd September,2026.0,Unprovoked,USA,Florida,New Smyrna Beach,Surfing,Unknown mMale,M,?,...,Unknown,Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1st September,2026.0,Unprovoked,USA,Florida,30 miles off Pensacola,Spearfishing,Brandon Hurst,M,40,...,300lb (135kg) Bull shark,Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,31st August,2026.0,Unprovoked,USA,Massachusetts,Norton Point Edgartown Marthas Vinyard,Swimming,Unknown Female,F,20's,...,Sandbar or Brown shark ( 2- 2.1m) 6-7ft,Kevin McMurray Trackingsharks.com: Keith Cowle...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,26th August,2026.0,Unprovoked,USA,Hawaii,"Ala Moana Beach Park, Oahu",Surfing,Unknown Female,F,?,...,Tiger Shark,Keith Cowley: KHON: KITV:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,23rd August,2026.0,Unprovoked,USA,Florida,Boca Grande (island in the keys),Wading on a sandbar,David Daniel,M,43,...,Large shark,Keith Cowley: Todd Smith: NBC 6: ABC News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,19th August,2026.0,Provoked,Reunion Island,Saint-Gilles-les-Baines,Outer Reef Roches Noires,Spearfishiong,Male,M,?,...,Bull shark 2.5m (8.2 ft),Todd Smith: Local Report Zinfos 874:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11th August,2026.0,Provoked,Ireland,Waterford,Ardemore County,Fishing,Sebastian Achim,M,27,...,1.5m (5ft) Blue shark,Keith Cowley: David Bargh: Irish Times BBC Met...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,8th August,2026.0,Unprovoked,USA,Maine,Scarborough Beach Park,Operation of Rescue Torpedo,Greg Wilfert,M,71,...,Great White Shark,WGME: CBS News: Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,29th July,2026.0,Unprovoked,USA,South Carolina,Murrells Inlet Garden City,Swimming,Teenage boy,M,?,...,Small shark unknown,Clay Creswell: Keith Cowley: Kevin McMurray Tr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,25th July,2026.0,Unprovoked,USA,Florida,Daytona Beach Shores Volusia County,Swimming,Jacorey High,M,21,...,4ft shark unknown species,Fox 5 Atlanta: Fox 35 Orland: Keith Cowley: Ke...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,24th July,2026.0,Unprovoked,Bahamas,Not stated,Nort stated,Snorkeling,John Schweizer,M,69,...,Caribbean Reef Shark 1.5 - 2.1m,NBC: CT Insider: CT Post: Keith Cowley:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,24th July,2026.0,Unprovoked,Fiji,Not stated,Not stated,Spearfishing,Henry Gibbs,M,?,...,Gray Reef Shark,Surfer: Kevin McMurray Trackingsharks.com: Sim...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,21st July,2026.0,Unprovoked,Australia,Queensland,Bundaberg,Hydrofoiling,David Seymour,M,?,...,3m shark unidentified,9 News: Simon De Marchi:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18th July,2026.0,Unprovoked,Australia,Tasmania,Coral Point Bruny Island,Spearfishing,Unknown,M,31,...,Broadnose Sevengill shark 2m,Sky News: ABC News: Keith Cowly: David Bargh:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3rd July,2026.0,Unprovoked,USA,New York,Jones Beach State Park Long Island,Swimming,Unknown,M,?,...,Baby Sand Tiger shark,NY Post: PIX II: Keith Cowley: Simon De Marchi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
shark_attack.nunique()

Date              6128
Year               261
Type                14
Country            257
State              956
Location          4662
Activity          1617
Name              5828
Sex                 12
Age                178
Injury            4229
Fatal Y/N           12
Time               493
Species           1772
Source            5447
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

In [10]:
shark_attack.describe()

              Year  original order
count  7123.000000     6799.000000
mean   1936.649586     3401.152081
std     269.808177     1963.076319
min       0.000000        2.000000
25%    1948.000000     1701.500000
50%    1987.000000     3401.000000
75%    2010.000000     5100.500000
max    2026.000000     6802.000000

In [ ]:
#coverte the year and age in a interger

#Rplace the Sex into Female and Male

#Convert the FATAL to Y/N