In [3]:
import pandas as pd

In [6]:
sharkflix_df = pd.read_csv("C:/Ironhack Data Analysis - Sep2026/Ironhack_Projects/Unit_2/shark_attacks_cleaned.csv")

In [7]:
sharkflix_df

,date,year,type,country,state,activity,name,sex,age_group,injury,fatal_y/n,species,time_group
0,18th September,2026.0,Unprovoked,australia,Western Australia,Swimming,Greg O'Neil,M,Middle-aged Adult,Body not recovered,y,Great White Shark 6m (20ft),Morning
1,13th September,2026.0,Unprovoked,australia,Western Australia,Surfing,Mel Ismail,M,Middle-aged Adult,Foot lost in attack,n,Unknown,Morning
2,7th September,2026.0,Unprovoked,usa,Hawaii,Surfing,Wants to remain anonymous,M,Young Adult,Scrapes on inside of legs,n,Tiger Shark suspected,Afternoon
3,2nd September,2026.0,Unprovoked,usa,Florida,Surfing,Unknown mMale,M,Unknown,Injury to right foot,n,Unknown,Morning
4,1st September,2026.0,Unprovoked,usa,Florida,Spearfishing,Brandon Hurst,M,Adult,Bites to both forearms,n,300lb (135kg) Bull shark,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2107,Mar-2000,2000.0,Unprovoked,usa,Louisiana,Spearfishing,Kurt Bickel,M,Adult,"No injury to diver, speargun damaged",n,"Shortfin mako shark, 3 m to 3.4 m [10' to 11']",Afternoon
2108,21-Feb-2000,2000.0,Unprovoked,usa,Florida,NaN,male,M,Young Adult,Right calf bitten,n,NaN,Afternoon
2109,19-Feb-2000,2000.0,Unprovoked,south africa,Western Cape Province,Body surfing,Dr. Weich,M,Unknown,Foot bitten,n,"White shark, 2.5 m",Afternoon
2110,01-Feb-2000,2000.0,Unprovoked,australia,South Australia,Surfing,Anthony Hayes,M,Young Adult,Hand bitten,n,3 m [10'] shark,Unknown
2111,2000,2000.0,Watercraft,usa,Florida,Fishing for tarpon,"boat: occupant, Terry Winters",M,Unknown,No injury to occupant; shark bit propeller,n,Hammerhead shark,Unknown

In [ ]:
# Count the recorded shark attaks for each state and show the 15 states with the most attacks
sharkflix_df["state"].value_counts().head(15)

state
Florida                  699
New South Wales          191
Hawaii                   178
Western Australia        151
California               149
Queensland               111
South Carolina            94
North Carolina            78
Western Cape Province     57
Eastern Cape Province     53
South Australia           46
Texas                     42
Victoria                  36
KwaZulu-Natal             35
New York                  19
Name: count, dtype: int64

In [10]:
# Define the 6 locations we selected for the SharkFlix analysis
top_6_states = [
    "Florida",
    "Hawaii",
    "California",
    "New South Wales",
    "Western Australia",
    "Queensland"
]

# Create a new DataFrame containing only these 6 locations
sharkflix_df = sharkflix_df[
    sharkflix_df["state"].isin(top_6_states)
].copy()

In [11]:
# Count the recorded shark attacks in each of the 6 selected locations
sharkflix_df["state"].value_counts()

state
Florida              699
New South Wales      191
Hawaii               178
Western Australia    151
California           149
Queensland           111
Name: count, dtype: int64

In [14]:
sharkflix_df

,date,year,type,country,state,activity,name,sex,age_group,injury,fatal_y/n,species,time_group
0,18th September,2026.0,Unprovoked,australia,Western Australia,Swimming,Greg O'Neil,M,Middle-aged Adult,Body not recovered,y,Great White Shark 6m (20ft),Morning
1,13th September,2026.0,Unprovoked,australia,Western Australia,Surfing,Mel Ismail,M,Middle-aged Adult,Foot lost in attack,n,Unknown,Morning
2,7th September,2026.0,Unprovoked,usa,Hawaii,Surfing,Wants to remain anonymous,M,Young Adult,Scrapes on inside of legs,n,Tiger Shark suspected,Afternoon
3,2nd September,2026.0,Unprovoked,usa,Florida,Surfing,Unknown mMale,M,Unknown,Injury to right foot,n,Unknown,Morning
4,1st September,2026.0,Unprovoked,usa,Florida,Spearfishing,Brandon Hurst,M,Adult,Bites to both forearms,n,300lb (135kg) Bull shark,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2104,10-Mar-2000,2000.0,Watercraft,australia,New South Wales,Rowing,boat of Scot's College rowers,NaN,Unknown,No Injury to occupants,n,2 m to 2.5 m [6.75' to 8.25'] shark,Unknown
2105,09-Mar-2000,2000.0,Watercraft,australia,New South Wales,Rowing,boat of Al Hattersly,NaN,Unknown,No injury to occupants; oar bitten,n,NaN,Unknown
2106,02-Mar-2000,2000.0,Unprovoked,australia,New South Wales,Swimming,Jack Dasey,M,Unknown,Survived,n,NaN,Unknown
2108,21-Feb-2000,2000.0,Unprovoked,usa,Florida,NaN,male,M,Young Adult,Right calf bitten,n,NaN,Afternoon
2111,2000,2000.0,Watercraft,usa,Florida,Fishing for tarpon,"boat: occupant, Terry Winters",M,Unknown,No injury to occupant; shark bit propeller,n,Hammerhead shark,Unknown

In [15]:
# Save the new SharkFlix dataset as a CSV file without the old DataFrame index
sharkflix_df.to_csv("sharkflix_top6_clean.csv", index=False)